/* org.agiso.core.logging.log4j.LogContext (2011-12-23)
 * 
 * LogContext.java
 * 
 * Copyright 2011 agiso.org.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.agiso.core.logging.log4j;

import org.apache.log4j.MDC;

/**
 * Used to store to use global info for logging purposes.<br>
 * 
 * This method prevent passing all the data you want to see in your logs in all
 * the methods.<br>
 * 
 * Please configure log4j with the data provided by this class such as
 * <code>log4j.appender.CONSOLE.layout.ConversionPattern=%d{HH:mm:ss-SSS} [%t]
 * %X{session_id} %p %X{login} %C.%M(%L) | %m%n</code>
 * where <code>session_id</code> and <code>login</code> are objects stored in
 * the log context.<br>
 * 
 * Based on code generated by Celerio, a Jaxio tool. http://www.jaxio.com/
 * 
 * @author Karol Kopacz
 * @since 1.0
 */
public abstract class LogContext {
	/**
	 * Get the context identified by the key parameter.
	 */
	public static Object get(String key) {
		return MDC.get(key);
	}

	/**
	 * Put a context value (the o parameter) as identified with the key parameter
	 * into the current thread's context map.
	 */
	public static void put(String key, Object o) {
		MDC.put(key, o);
	}

	/**
	 * Remove the the context identified by the key parameter.
	 */
	public static void remove(String key) {
		MDC.remove(key);
	}

	/**
	 * Remove all the object put in this thread context.
	 */
	public static void resetLogContext() {
		if(MDC.getContext() != null) {
			MDC.getContext().clear();
		}
	}
}
